### ISSUE TITLE
Callout testing

### ISSUE THREAD

**Issue by tannerhelland** [jpbro/VbPcre2#1]
I haven't done a lot of testing with "callout" features, but the newest DLL appears to work with callouts if the following VB6 changes are made:

1) Inside `pcreCalloutProc()`, change the `CopyMemory` line to this:

`CopyMemory ByVal VarPtr(lt_CalloutBlock), ByVal p_CalloutBlockPointer, LenB(lt_CalloutBlock)`

The following `Debug.Print lt_CalloutBlock.Version` line should now produce 0, as expected.

2) To test, add this declaration to `CPCre.cls`:

`Private Declare Function pcre2_callout_enumerate Lib "pcre2-16.dll" Alias "_pcre2_callout_enumerate_16@12" (ByVal p_CompiledPattern As Long, ByVal pCalloutAddress As Long, ByRef p_CalloutDataPointer As Long) As Long`

...and inside the `Execute()` function, replace this line:

`Debug.Print "Callout: " & pcre2_set_callout(l_MatchData, AddressOf pcreCalloutProc, ObjPtr(Me))`

...with this:

`pcre2_callout_enumerate l_CompiledRegex, AddressOf pcreCalloutProc, ObjPtr(Me)`

The callout function is now invoked successfully!

`pcre2_set_callout()` should also hypothetically work, however it needs a match context to be passed, so we'd need to add a declaration for `pcre2_match_context_create()` and of course invoke it prior to using `pcre2_set_callout`.

Thank you again for your work on this!  I am far from an expert in regex, so I'll test where I can, but I may leave the complicated stuff to the experts... ;)

**Comment by jpbro** [comment]
Hi Tanner, thanks a lot for this! I've been able to implement support for pcre2_enumerate_callouts based on your advice above :)

To be honest, I'm not a regex expert either, but it's been fun working on something that the VB6 community can get some use from - it's nice to give back a bit.

Regarding enumerating callouts specifically - I don't even really know what a typical use case is! I've tried to find an example, but so far I have been unsuccessful (I'll look a bit harder soon, been a bit pre-occupied).

Because I don't know a use-case, I'm not sure if the way I've implemented it is useful. Currently, you can set the CPcre.RegexOptions.EnumerateCallouts = True and pcre2_enumerate_callouts will be called before matching is attempted. This will raise a CalloutEnumerateReceived event for each callout in the regex. If you set the p_ReturnValue to non-zero it will cancel enumeration and skip subsequent matching. If you leave it a 0, then everything proceeds normally. 

I'll have to do more research to see if this is a good approach. Some other ideas:

- Maybe it's better to have a separate EnumerateCallouts method, and not do the enumeration before matching?

- Do any of the parameters in CalloutEnumerateReceived need to be ByRef so that we can make modifications to the regex? Not sure if this is something that can/should be done.

- Maybe we need to have 3 actions for the p_ReturnValue - 0 = proceed normally, <0 = cancel enumeration and matching, >0 = cancel enumeration and proceed with matching? In this case an enumeration might be appropriate as opposed to a raw Long.

Thanks again for your efforts!

**Comment by tannerhelland** [comment]
> Regarding enumerating callouts specifically - I don't even really know what a typical use case is! I've tried to find an example, but so far I have been unsuccessful (I'll look a bit harder soon, been a bit pre-occupied).

Same here!  It's entirely possible that enumerating callouts is not actually that useful, in which case I wouldn't blame you for dropping the feature entirely.  (I mainly just wanted to make sure I'd built the DLL correctly, in a way that didn't break callouts based in VB6 projects.)  I will keep a lookout too for a potential use-case, but maybe only the hardest of hardcore regex users need something like that...

Either way, I really like the idea of raising the enumerations as "CalloutEnumerateReceived" events.  Great thinking.

Since I am not that certain on the three other ideas you've raised, I'm going to read more of the pcre documentation and try to formulate some useful input.  In the meantime, I may send over some trivial pull requests (like copy+pasting enums from the original pcre source).  

Thanks for letting me participate.  :)

**Comment by jpbro** [comment]
The PCRE2 documentation only seems to have this to say about enumerating callouts:

"A script language that supports the use of string arguments in callouts might like to scan all the callouts in a pattern before running the match."

Anyway, the work is done and I think it's potentially useful as is, so I'll leave it for now and move on to others things. We can always revisit if as necessary. Thanks again Tanner!
