### ISSUE TITLE
Pre-built VBPCRE2Test.exe in /bin folder is out-of-date

### ISSUE THREAD

**Issue by tannerhelland** [jpbro/VbPcre2#23]
Subject line says it all.  :)  Running the current bin/VBPCRE2Test.exe instance throws an error.

Manually rebuilding VBPCRE2Test.exe using the latest source, then manually copying the .exe into the /bin folder and trying again works as expected.

Thank you for your continued work on this!

**Comment by jpbro** [comment]
Thanks Tanner, should be fixed in https://github.com/jpbro/VbPcre2/commit/d3e8f59fc3b5ed760338faebb503c68195399be0 . A bit of a "duh" moment from me...I'm used to working with Binary Compatibility on for my daily work, and forgot that wasn't the case here. 

I guess this raises the question as to whether now is a good time to turn binary compatibility on for VbCpre2...as far as I am concerned it is a good time since the interface has stabilized, but I'll wait a bit in case anyone disagrees.

Thanks again for the feedback, it's always nice to get it when your project doesn't get a lot of traffic :)

**Comment by tannerhelland** [comment]
I'm sorry that this hasn't gotten more traffic + feedback from the VB6 community.  It's an excellent project.  Maybe too many of them are still afraid of GitHub.  :/

(Although if I'm being honest, maybe it's a *good* thing that the average VB6 dev doesn't know about regex.  I can only imagine what kind of hellish things they'd concoct with it - lol!)

I'll leave the broader question of binary compatibility up to you.  I think @dragokas uses the library in production code, so maybe he can chime in.  (If he hasn't run into issues in the past year, the interface is likely good to go!)

**Comment by dragokas** [comment]
I didn't update my wrapper since jpbro made final COM-release.
Anyway I'm using only code, not a dll. So, it's not important for me.

tannerhelland, thanks for this notice about new PCRE,
and thanks jpbro for continuing your work on project.
